#!/bin/bash


echo "All variables: $@"
echo "number of varibles pass: $#"
echo "script name: $0"
echo "currect working directory: $PWD"
echo "home diectory of current user: $HOME"
echo "which user running this script: $USER"
echo "Host name: $HOSTNAME"
echo "process id of shell script: $$ "